import React from 'react';
import './App.css';
import $ from 'jquery';
import CSS from 'csstype';
import {
    BrowserRouter as Router,
    Switch,
    Route,
    RouteComponentProps,
    Link,
    matchPath,
    withRouter,
} from 'react-router-dom';
import * as firebase from 'firebase/app';
import { SignIn, SignOut } from './UserManagement';
import { Dashboard } from './Dashboard';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faBalanceScale, faBolt, faGlobeAmericas, faHandshake } from '@fortawesome/free-solid-svg-icons'
import { ViewContracts, ViewDashboards } from './ViewPages';

function HomePage() {
    return (
        <div>
            <div className="jumbotron">
                <h1 className="display-4">Fides: A Credit-Score For Trust</h1>
                <p className="lead">Innovative, easy to use, distributed trust-tracking and arbitration software: so you always know if someone is trustworthy, no matter where they come from.</p>
                <hr className="my-4" />
                <p>If you already have an account, or want one, just click the&nbsp;
                    <kbd>Sign Up</kbd> button below, or the <kbd>Sign In</kbd> button
                    above! Accounts are free and super fast to make, and we will not
                    harass you with marketing emails.</p>
                <div className="lead">
                    <div className="btn-group">
                        <Link className="btn btn-primary btn-lg" to="/signin" role="button">Sign Up</Link>
                        <a className="btn btn-secondary btn-lg" href="https://github.com/christopherdumas/Fides/blob/master/README.md" role="button">Learn More</a>
                    </div>
                </div>
            </div>
            <div className="row">
                <div className="col-md">
                    <h1 style={{ textAlign: 'center' }}><FontAwesomeIcon icon={faBalanceScale} /></h1>
                    <h2 style={{ textAlign: 'center' }}>Algorithmic Justice</h2>
                    <p>Your trust score is generated by Fides based on a complex
                        system of ratings aggregated over the entire list of
                        structured interactions ("contracts") that you've had with
                        other Fides users. It weights each user's rating of you
                        based on that user's amount of experience with you (adjusted
                        by a carefully-calibrated Gaussian distribution) and on the
                        rating user's own trust score &mdash; that way, nefarious
                        actors won't be able to ruin your reputation.</p>
                </div>
                <div className="col-md">
                    <h1 style={{ textAlign: 'center' }}><FontAwesomeIcon icon={faGlobeAmericas} /></h1>
                    <h2 style={{ textAlign: 'center' }}>Global Ratings For Everyone</h2>
                    <p>Fides takes a holistic approach to your, and other people's, trust-scores:
                        the score isn&#39;t limited to one particular service or
                        job, like a credit score, Ebay score, or Yelp score
                        &mdash; instead, it is intelligently based on any
                        interaction that you have mutually agreed to with
                        someone else, and promised to complete. As part of attempting to be a more general framework for trust, we also offer arbitrated "contracts" allowing a third part to judge both other parties.</p>
                </div>
            </div>
            <div className="row">
                <div className="col-md">
                    <h1 style={{ textAlign: 'center' }}><FontAwesomeIcon icon={faBolt} /></h1>
                    <h2 style={{ textAlign: 'center' }}>Lightening-Fast Performance</h2>
                    <p>Everything on Fides is updated as soon as new information hits our servers, meaning
                        that all the information you are looking at is garunteed to be
                        as up-to-date as possible at all times. No set refresh times,
                        and no need to hit that refresh button yourself! Meanwhile,
                        our entire system is structured
                        for maximum reliable performance, so when you need it, Fides is
                        always read to go!</p>
                </div>
                <div className="col-md">
                    <h1 style={{ textAlign: 'center' }}><FontAwesomeIcon icon={faHandshake} /></h1>
                    <h2 style={{ textAlign: 'center' }}>Distributed Rating</h2>
                    <p>We do not have one central authority choosing who gets to
                        be marked as trustworthy and who does not &mdash; instead,
                        all of your peers will rate you using an easy to use and
                        proportionate rating system based on how well
                        <em>they</em>&nbsp; were satisfied with their "contract"
        with you. Make your peers happy, and more people will be
        willing to trust you, because your score will be higher!</p>
                </div>
            </div>
        </div>
    );
}

interface NavProps extends RouteComponentProps<any> {
    location: any
}

interface State {
    signedIn?: boolean
    uid?: string
}

class NavbarRaw extends React.Component<NavProps, State> {
    constructor(props: NavProps) {
        super(props);
        this.state = {
            uid: "!!unknown!!",
            signedIn: false,
        };
    }

    componentDidMount() {
        firebase.auth().onAuthStateChanged(user => {
            if (user) {
                this.setState({ signedIn: true, uid: user.uid });
            } else {
                this.setState({ signedIn: false, uid: "" });
            }
        });
    }

    render() {
        const url = this.props.location.pathname;
        const actives = [
            (!!matchPath(url, '/contracts/:uniqid') ||
                !!matchPath(url, '/contracts')) ? 'active' : '',
            !!matchPath(url, '/users') ? 'active' : '',
            !!matchPath(url, '/dashboard/:uid') ? 'active' : '',
        ];
        const universals = [
            <li key="1" className="nav-item">
                <Link className={`nav-link ${actives[0]}`} to="/contracts">Contracts</Link>
            </li>,
            <li key="2" className="nav-item">
                <Link className={`nav-link ${actives[1]}`} to="/users">Users</Link>
            </li>
        ];
        const signedIn = [
            <ul key="1" className="navbar-nav">
                {universals}
                <li key="1" className="nav-item">
                    <Link className={`nav-link ${actives[2]}`} to={`/dashboard/${this.state.uid}`}>Dashboard</Link>
                </li>
            </ul>,
            <div key="2" className="form-inline ml-auto">
                <button className="btn btn-sm btn-outline-warning" onClick={e => {
                    e.preventDefault();
                    $('#myModal').modal('show');
                }} type="button">Sign Out</button>
            </div>
        ];
        const signedOut = [
            <ul key="1" className="navbar-nav">
                {universals}
            </ul>,
            <div key="2" className="form-inline ml-auto">
                <Link className="btn btn-sm btn-outline-warning" to="/signin">Sign In</Link>
            </div>
        ]
        return (
            this.state.uid === "!!unknown!!" ?
                (<div className="spinner-border ml-auto text-secondary"
                    role="status"
                    aria-hidden="true"></div>) : (
                    this.state.signedIn ?
                        signedIn :
                        signedOut)
        );
    }
}

const Navbar = withRouter(NavbarRaw);

function App() {
    const footerStyle: CSS.Properties = {
        backgroundColor: '#eee',
        padding: '20px 20px 20px 20px'
    };
    return (
        <div>
            <Router>
                <div>
                    <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
                        <Link className="navbar-brand" to="/">Fides</Link>
                        <button className="navbar-toggler navbar-right"
                            type="button" data-toggle="collapse"
                            data-target="#navbarNav" aria-controls="navbarNav"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span className="navbar-toggler-icon"></span>
                        </button>
                        <div className="collapse navbar-collapse" id="navbarNav">
                            <Navbar />
                        </div>
                    </nav>
                    <SignOut />
                    <br />
                    {/* A <Switch> looks through its children <Route>s and
                    renders the first one that matches the current URL. */}
                    <div className="container">
                        <Switch>
                            <Route path="/signin" component={SignIn}></Route>
                            <Route path="/dashboard/:uid" component={Dashboard}></Route>
                            <Route path="/contracts" exact component={ViewContracts}></Route>
                            <Route path="/contract/:uniqid" component={ViewContracts}></Route>
                            <Route path="/users" component={ViewDashboards}></Route>
                            <Route path="/">
                                <HomePage />
                            </Route>
                        </Switch>
                    </div>
                </div>
            </Router>
            <footer style={footerStyle}>
                <p>
                    <small>
                        We are not responsible for any real-world consequences that your use of this application has on your real-world reputation. The use of this system is your choice, and by choosing to use it you accept the consequences, which may include others looking up your name on this application to determine how trustworthy you are.
            </small> | <small>Inspired by philosopher and economist Murray N. Rothbard's speculations in <a href="https://mises.org/library/society-without-state">"Society without a State"</a></small>
                </p>
            </footer>
        </div >
    );
}

export default App;
